classes:
  warrior:
    display-name: "Warrior"
    description: "A mighty melee fighter."
    icon: "IRON_SWORD"
    stats:
      strength: 10
      defense: 5
      speed: 2
  archer:
    display-name: "Archer"
    description: "A nimble ranged attacker."
    icon: "BOW"
    stats:
      dexterity: 10
      speed: 5
      strength: 2
  mage:
    display-name: "Mage"
    description: "A powerful spellcaster."
    icon: "BLAZE_ROD"
    stats:
      intelligence: 10
      wisdom: 5
      speed: 2