name: SandMMO
version: 1.0
main: com.sandmmo.SandMMO
api-version: 1.21
authors: [ManOfTheSand]
description: |
  §6§lSandstorm MMO §r§7- A mystical desert-themed RPG experience
  with custom classes, skills, and progression systems!
depend: [MythicMobs]
softdepend: [Eco, DecentHolograms]

commands:
  class:
    description: Open the class selection menu
    usage: /class [select|info] [className]
    aliases: [classes, chooseclass]
    permission: sandmmo.class.select
  sandmmo:
    description: Reload the SandMMO plugin.
    usage: /sandmmo reload

permissions:
  sandmmo.class.select:
    description: Allows players to select classes
    default: true
