name: SandMMO
version: 1.0.0
main: com.sandcore.mmo.SandCoreMain
api-version: 1.21
commands:
  sandmmo:
    description: "Main command for SandMMO plugin"
    usage: "/sandmmo <reload|admin stats ...>"
    permission: sandmmo.reload
  stats:
    description: "View your stats"
    usage: "/stats"
permissions:
  sandmmo.admin.stats:
    description: "Allows the admin to update player stats."
    default: op
  sandmmo.reload:
    description: "Allows reloading configurations"
    default: op