name: SandMMO
version: 1.0.0
main: com.sandmmo.SandMMO
api-version: 1.21
commands:
  class:
    description: Open class selection
  stats:
    description: View your stats
  sandmmo:
    description: Reload configurations
    permission: sandmmo.reload
permissions:
  sandmmo.reload:
    default: op