name: SandMMO
version: 1.0.0
main: com.sandcore.mmo.SandCoreMain
api-version: 1.21
commands:
  class:
    description: Choose your class
  stats:
    description: View your stats
  sandmmo:
    description: Reload plugin configurations
    usage: /sandmmo reload
    permission: sandmmo.reload
permissions:
  sandmmo.reload:
    description: Allows reloading configurations
    default: op